spring:
  application:
    name: getaway

  cloud:
    nacos:
      discovery:
        server-addr: "127.0.0.1:8848"
    sentinel:
      transport:
        dashboard: "127.0.0.1:8850"

    gateway:
      routes:
        - id: first-client
          uri: lb://first-client
          predicates:
            - Path=/first-client/**
          filters:
            - RewritePath=/first-client/(?<segment>.*), /$\{segment}

        - id: second-client
          uri: lb://second-client
          predicates:
            - Path=/second-client/**
          filters:
            - RewritePath=/second-client/(?<segment>.*), /$\{segment}
server:
  port: 8080
