eureka:
  instance:
    appname: getaway
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: getaway
server:
  port: 8080

zuul:
  routes:
    firstClient:
      path: /first-client/**
      serviceId: first-client
