spring:
  zipkin:
    base-url: "http://127.0.0.1:9411"
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1
  application:
    name: first-client
  cloud:
    nacos:
      discovery:
        server-addr: "127.0.0.1:8848"
    sentinel:
      datasource:
        ds:
          nacos:
            serverAddr: "127.0.0.1:8848"
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            ruleType: flow
            dataType: json
      transport:
        dashboard: "127.0.0.1:8850"
server:
  port: 8001
