spring:
  application:
    name: second-client
  cloud:
    nacos:
      discovery:
        server-addr: "127.0.0.1:8848"
    sentinel:
      transport:
        dashboard: "127.0.0.1:8850"

server:
  port: 8002

feign:
  client:
    config:
      default:
        readTimeout: 3000
        connectTimeout: 3000
  hystrix:
    enabled: true